In [5]:
import torch
import torch.nn as nn

# 創建一個 Conv1d 層
# in_channels=1: 輸入通道數為 1
# out_channels=1: 輸出通道數為 1
# kernel_size=3: 卷積核大小為 3
conv1d = nn.Conv1d(in_channels=2, out_channels=2, kernel_size=3, padding=1, stride=1)

# 創建一個隨機數據作為輸入
# (batch_size=1, channels=1, length=10)
input_data = torch.randn(2, 2, 5)

# 將輸入數據通過 Conv1d 層
output_data = conv1d(input_data)

input_data, output_data, conv1d.weight.data, conv1d.bias.data



tensor([[[ 2.1748,  0.6858, -0.1742, -2.4586,  0.3183],
         [-0.5036,  1.0337, -0.9911, -0.6379,  0.5337]],

        [[ 0.5633,  1.0901,  0.6712,  0.5705,  1.0497],
         [ 1.1368,  1.2007, -0.2224,  0.8932, -0.9019]]])

In [11]:
print('input_data: \n', input_data, '\n')
print('output_data: \n', output_data, '\n')
print('conv1d.weight.data: \n', conv1d.weight.data, '\n')
print('conv1d.bias.data: \n', conv1d.bias.data, '\n')


input_data: 
 tensor([[[ 2.1748,  0.6858, -0.1742, -2.4586,  0.3183],
         [-0.5036,  1.0337, -0.9911, -0.6379,  0.5337]],

        [[ 0.5633,  1.0901,  0.6712,  0.5705,  1.0497],
         [ 1.1368,  1.2007, -0.2224,  0.8932, -0.9019]]]) 

output_data: 
 tensor([[[ 0.8462,  0.8953, -0.0970,  0.1382,  0.6288],
         [-0.7393, -1.0093, -0.8678,  1.2026,  1.0398]],

        [[ 1.1388,  0.4108,  0.2892,  0.3494, -0.0661],
         [ 0.1889, -0.6460, -0.7982, -0.3143, -0.9407]]],
       grad_fn=<ConvolutionBackward0>) 

conv1d.weight.data: 
 tensor([[[ 0.0905,  0.1911, -0.2181],
         [-0.3692,  0.3786,  0.4044]],

        [[-0.3941, -0.3882,  0.0995],
         [-0.1894,  0.1484,  0.1131]]]) 

conv1d.bias.data: 
 tensor([ 0.3529, -0.0055]) 



: 